export function dispatchExcelKeysMapping() {
    const keysMapping: { [key: string]: string } = {
        'ordernumber': 'orderNumber',
        'invoicenumber': 'invoiceNumber',
        'invoicedate': 'invoiceDate',
        'pickuplocation': 'pickupLocation',
        'pickupdate': 'pickupDate',
        'consigneeid': 'consigneeId',
        'consigneename': 'consigneeName',
        'incoterms': 'incoTerms',
        'commoditytype': 'commodityType',
        'materialid': 'materialId',
        'materialname': 'materialName',
        'materialcategory': 'materialCategory',
        'materialdiscription': 'materialDiscription',
        'qty': 'quantity',
        'uom': 'uom',
        'hscode': 'hsCode',
        'hscodediscription': 'hsCodeDiscription',
        'noofpackages': 'noOfPackages',
        'packagetype': 'packageType',
        'packageweight': 'packageWeight',
        'length': 'length',
        'width': 'width',
        'height': 'height',
        'specialinstructions': 'specialInstructions',
        'hzgoods': 'hzGoods',
        'requesteddateofdelivery': 'requestedDateOfDelivery',
        'modeofshipment': 'modeOfShipment',
        'carrierid': 'carrierId',
        'carriername': 'carrierName',
        'bookingreference': 'bookingReference',
        'containernumber': 'containerNumber',
        'hbl': 'hbl',
        'mbl': 'mbl',
        'awb': 'awb',
        'hawb': 'hawb',
        'mawb': 'mawb',
    }
    return keysMapping;
}